import { AUTHENTICATED_PATH, AUTHENTICATED_PARAM, AUTH_PROP } from "./authenticated";
import { NOT_AUTHENTICATED_PATH, NOT_AUTHENTICATED_PARAM, NOT_AUTH_PROP } from "./not-authenticated";

export {
  NOT_AUTHENTICATED_PARAM,
  NOT_AUTHENTICATED_PATH,
  AUTHENTICATED_PARAM,
  AUTHENTICATED_PATH,
  NOT_AUTH_PROP,
  AUTH_PROP
}